version: "3.8"
services:
    mysql-server:
        image: mysql:8.0.27
        platform: linux/x86_64
        ports:
            - 3399:3306
        restart: always
        volumes:
            - ./mysql/data:/var/mysql/sql # nếu để dòng này thì dòng bên dưới sẽ không có tác dụng
            - ./mysql/sql/:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
    web:
        build: ./www
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - "mysql-server"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 3306:80 
            # port default is 8888
        restart: always
        environment:
            - PMA_HOST=mysql-server
        depends_on:
            - "mysql-server"
